- name: Ensure that the defined redis version is downloaded {{ redis_version }}
  unarchive:
    src: "https://github.com/redis/redis/archive/7.0.7.tar.gz-{{ redis_version }}.tar.gz"
    dest: /tmp/
    remote_src: yes
  
  
- name: Ensure the build time dependencies are met
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
  

- name: Ensuring redis server is installed on the system
  make:
    chdir: "/tmp/redis-{{ redis_version }}"
    target: install
  

